### ISSUE TITLE
QR code broken in Firefox

### ISSUE THREAD

**Issue by arctica** [Place1/wg-access-server#59] opened 2020-07-07 11:00 UTC
Using current FF 78.0.1 under OSX, the QR code image seems to be broken. See attached screenshot. It worked fine in Safari.

![Screen Shot 2020-07-07 at 17 55 57](https://user-images.githubusercontent.com/870630/86770930-fccdb100-c040-11ea-98a7-419ef42942d5.png)

**Comment by Place1** [comment] 2020-07-18 03:52
Hey, I can't reproduce this using FF 78 on Linux or Mac.

Please reopen this if you can still reproduce this and can provide more information such as console output.

Apologies I can't be more helpful.

**Comment by arctica** [comment] 2020-07-18 12:22
@Place1 not sure how to re-open the issue but I did now check the console output and saw this:

```Blocked http://vpn....:8000/ from extracting canvas data because no user input was detected.```

I have a few privace related settings active in FF so I think one of them prevents canvas fingerprinting. I've tried disabling the fingerprinting blocker but that didn't seem to help. Maybe it would be better to create the images as a jpeg/png/bitmap and use data urls?

It's weird because I definitely interacted with the page because otherwise I couldn't get that new device modal but FF thinks I didn't...

**Comment by Place1** [comment] 2020-07-20 11:54
@arctica it may be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1446472

wg-access-server uses [this lib](https://www.npmjs.com/package/qrcode) to generate QR codes on the frontend; perhaps we could try other libs but it seems like your issue will be present with other libs because of the common use of the canvas api.

**Comment by arctica** [comment] 2020-07-20 12:09
> @arctica it may be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1446472
> 
> wg-access-server uses [this lib](https://www.npmjs.com/package/qrcode) to generate QR codes on the frontend; perhaps we could try other libs but it seems like your issue will be present with other libs because of the common use of the canvas api.
> 
> i'd be happy to accept a PR for this issue :)

Yes I think this is exactly the issue, good find. Turning off "privacy.resistFingerprinting" in about:config makes the QR code work again. Weird that toggling this via the UI didn't seem to work. It's unfortunate that FF has this bug open for 2 years already and it even breaks popular pages like whatsapp. Don't think switching libraries will do much as like you said they probably suffer from the same. In the bugreport for FF they say that rendering to canvas should not be an issue. I guess that library might read it as well for some reason? Not sure. I should probably file a bugreport with that QR lib.

**Comment by Place1** [comment] 2020-10-18 05:46
There's not much I can do about this issue right now so i'm going to close it. Please reopen if there's been any update i've missed :)

**Closed by Place1** 2020-10-18 05:46 UTC
