### ISSUE TITLE
Allow adjustment of AllowedIPs and removal of DNS

### ISSUE THREAD

**Issue by KimchaC** [Place1/wg-access-server#22] opened 2020-04-08 11:40 UTC
Hi,

I have another feature request.

### Feature request

I am using wireguard to connect to our internal company network. So only company internal traffic should go through the VPN.

Can you please make AllowedIPs customizable from the config?

And the same goes for DNS. When connected through the VPN I don't want DNS to go through the VPN so it would be great if that could be disabled completely.

### Workaround
For anyone else who is looking for this functionality in the meantime, I have figured out a workaround.

- Copy the file `/website/build/static/js/main.086d0b42.chunk.js` from the container
- Adjust the AllowedIPs part inside of it
- Comment out the DNS section with a "#". Don't remove it as it will mess up the dynamic parameters
- Add this to your docker-compose volumes section `- "./patch/main.086d0b42.chunk.js:/website/build/static/js/main.086d0b42.chunk.js:rw"`
- Restart the container

This will replace `main.086d0b42.chunk.js` with your customized version and cause the frontend to generate wireguard configs with your desired options.

**Comment by Place1** [comment] 2020-04-12 03:49
This is something i'm planning to add and use myself as well.

I've recently added support for configuring what traffic the VPN will route server side; my next step will be to propagate this into the generated Client device config files (AllowedIPs), add docs and release!

Can't give you a timeline but this feature is coming soon!

**Comment by Place1** [comment] 2020-04-12 05:52
Hey, i've implemented this now. Check it out using the `0.2.0-rc1` docker image tag.

You'll want to configure `vpn.rules` ([docs](https://place1.github.io/wg-access-server/configuration/#config-file-configyaml)) for your use-case.

For example:

```yaml
vpn:
  rules:
    allowedNetworks:
      - 192.168.0.0/24
```

or if you want any private networks to be routed

```yaml
vpn:
  rules:
    allowServerLAN: true
```

**Comment by KimchaC** [comment] 2020-04-12 08:53
Wow, you are amazing. Thank you. I will check it out next week!

**Comment by KimchaC** [comment] 2020-04-12 10:17
Ok, I was too excited about this and couldn't wait until next week.

It works very well, my only concern is that when you enable allowServerLAN it adds ALL private address spaces to the Allowed IPs: `10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16`.

I think this could have potential to cause issues. My understanding is that requests to any IP that matches the AllowedIPs will be routed through the VPN.

My home network is on 192.168.0.0/24 for example. So if I wanted to access my router on 192.168.0.1, it should theoretically go through the VPN and then fail.

When I tried it actually worked, so I am not sure what is going on there.

Another issue is that I could have multiple VPNs set up. One to AWS on 10.0.1.0/16, another one to Azure on 10.0.2.0/16.

And then let's say wg-access-server to my home network on 192.168.0.0/24. With the current config wg-access-server would hog all connections and probably fail the other VPNs.

So ideally `allowServerLAN` would detect what the local LAN is and only set that one. But I think that's probably why you implemented it the way you did... default docker config can't see the host's network interface and IP config. It only sees the docker0 network.

For most use-cases what you have is probably not an issue, so perhaps that's an ok default.

More advanced users can set it up using 
```
    allowServerLAN: false
    allowedNetworks:
      - 192.168.0.0/24 # My local LAN only
```

I also love that this doesn't just change the config generation, but also adjusts the iptables rules. That's awesome.

**Comment by KimchaC** [comment] 2020-04-12 10:18
Also, you haven't added dns.enable option to the documentation.

**Comment by Place1** [comment] 2020-04-13 08:21
> allowServerLAN it adds ALL private address spaces to the Allowed IPs

This is essentially by design and I intended this behaviour. I wanted a simple flag that users could use to just say "hey, anything my VPN server can connect to is fair game". If a user wants to limit private networks more explicitly then they can use the `allowedNetworks: []` config to white list specific CIDRs. Perhaps I can address this better in the docs!

> When I tried it actually worked, so I am not sure what is going on there.

The allowed ips config from the wireguard client apps is a little confusing. As far as I can tell all it does is update your route table, so it's possible you have a more specific route table entry for your router (possibly a 192.168.0.1/32) that would cause traffic to route directly to it.

> So ideally allowServerLAN would detect what the local LAN is and only set that one. But I think that's probably why you implemented it the way you did... default docker config can't see the host's network interface and IP config. It only sees the docker0 network.

Yeah, full circle haha. That's the intention. Even if a user runs wg-access-server in the host's network we have no idea what private networks are routeable but not on-link; so to avoid fluffing about with detection logic that result in something unexpected i thought it's be better to have explicit options.

Perhaps renaming `allowServerLAN` to something that better communicates that it's for forwarding traffic to any private ipv4 address would be better. 🤷

**Comment by Place1** [comment] 2020-04-13 08:21
I'm going to close this one now because it looks like you're cooking with gas now. Feel free to reopen if there's a bug in 0.2.0-rc1 breaking this new feature :)

**Closed** 2020-04-13 08:21 UTC
