### ISSUE TITLE
fatal error: thread exhaustion

### ISSUE THREAD

**Issue by KimchaC** [Place1/wg-access-server#30] opened 2020-04-13 08:01 UTC
I noticed wg-access-server crashed after a while on my server with this error:
```
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion
```

For now we can probably workaround it by adding this to the docker-compose.yml
```
    restart: always
```

I have attached the full log:
[wg-access-server-crash.log](https://github.com/Place1/wg-access-server/files/4468592/wg-access-server-crash.log)

**Comment by Place1** [comment] 2020-04-13 08:45
Interesting. How many devices were connected at the time of the crash (best guess will do).

**Comment by KimchaC** [comment] 2020-04-13 08:58
It would be 2 or 3 at most. Most likely 1 or 2.

**Comment by Place1** [comment] 2020-04-16 06:53
I haven't been able to reproduce this one. I've been running wg-access-server for months now without a crash.

From the trace it looks like a leak in wireguard-go but i'm not sure tbh.

**Comment by Place1** [comment] 2020-05-13 12:56
I'm going to close this because i can't really action anything until it's reproducible. :(

**Closed by Place1** 2020-05-13 12:56 UTC

**Comment by analogue** [comment] 2020-07-31 16:45
Having the same issue:
```
 63266 time="2020-07-30T09:41:36-05:00" level=info msg="starting wireguard server on 0.0.0.0:REDACTED" file="main.go:50"
 63267 time="2020-07-30T09:41:36-05:00" level=info msg="wireguard VPN network is REDACTED/24" file="main.go:60"
 63268 time="2020-07-30T09:41:36-05:00" level=info msg="starting dns server on 0.0.0.0:53 with upstreams: REDACTED" file="serv
 63269 time="2020-07-30T09:41:36-05:00" level=info msg="storing data in /data" file="contracts.go:55"
 63270 time="2020-07-30T09:41:36-05:00" level=info msg="web ui listening on 0.0.0.0:REDACTED" file="main.go:171"
 63271 runtime: program exceeds 10000-thread limit
 63272 fatal error: thread exhaustion
 63273 
 63274 runtime stack:
 63275 runtime.throw(0xda9c41, 0x11)
 63276         /usr/local/go/src/runtime/panic.go:774 +0x72
 63277 runtime.checkmcount()
 63278         /usr/local/go/src/runtime/proc.go:600 +0xac
 63279 runtime.mcommoninit(0xc01c01ee00)
 63280         /usr/local/go/src/runtime/proc.go:618 +0x73
 63281 runtime.allocm(0xc000040a00, 0xddd630, 0x0)
 63282         /usr/local/go/src/runtime/proc.go:1489 +0x150
 63283 runtime.newm(0xddd630, 0xc000040a00)
 63284         /usr/local/go/src/runtime/proc.go:1804 +0x39
 63285 runtime.startm(0x0, 0xc000047901)
 63286         /usr/local/go/src/runtime/proc.go:1969 +0x12a
 63287 runtime.wakep(...)
 63288         /usr/local/go/src/runtime/proc.go:2050
 63289 runtime.resetspinning()
 63290         /usr/local/go/src/runtime/proc.go:2430 +0x93
 63291 runtime.schedule()
 63292         /usr/local/go/src/runtime/proc.go:2531 +0x2a0
 63293 runtime.park_m(0xc0004e5080)
 63294         /usr/local/go/src/runtime/proc.go:2610 +0x9d
 63295 runtime.mcall(0x0)
 63296         /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
```

FWIW, sawtooth like memory comsumption over time:
![image](https://user-images.githubusercontent.com/26757/89057349-17830500-d323-11ea-8537-494a7ee9d5f8.png)

Self-built docker image from latest commit.
Can provide more details if needed.

**Comment by Place1** [comment] 2021-01-17 01:38
update for anyone watching this issue; there actually was a leak in wg-access-server that I fixed during during a big refactor in late 2020.

if you're running the latest version this issue should hopefully be resolved.

please open a new issue if you're seeing thread exhaustion or jigsaw memory usage again.
